//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.reuseIdentifier` struct is generated, and contains static references to 2 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `CustomCellResult`.
    static let customCellResult: Rswift.ReuseIdentifier<CustomTableViewCell> = Rswift.ReuseIdentifier(identifier: "CustomCellResult")
    /// Reuse identifier `CustomFav`.
    static let customFav: Rswift.ReuseIdentifier<CustomFavTableViewCell> = Rswift.ReuseIdentifier(identifier: "CustomFav")

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 12 localization keys.
    struct localizable {
      /// en translation:  Arabic
      ///
      /// Locales: en, fr
      static let arabic = Rswift.StringResource(key: "Arabic", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "fr"], comment: nil)
      /// en translation: Add a keyword
      ///
      /// Locales: en, fr
      static let keywords = Rswift.StringResource(key: "keywords", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "fr"], comment: nil)
      /// en translation: Already in favorites
      ///
      /// Locales: en, fr
      static let alertFav = Rswift.StringResource(key: "alertFav", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "fr"], comment: nil)
      /// en translation: Choose a languages
      ///
      /// Locales: en, fr
      static let languages = Rswift.StringResource(key: "languages", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "fr"], comment: nil)
      /// en translation: Choose your categories
      ///
      /// Locales: en, fr
      static let categories = Rswift.StringResource(key: "categories", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "fr"], comment: nil)
      /// en translation: Deutsch
      ///
      /// Locales: en, fr
      static let deutsch = Rswift.StringResource(key: "Deutsch", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "fr"], comment: nil)
      /// en translation: English
      ///
      /// Locales: en, fr
      static let english = Rswift.StringResource(key: "English", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "fr"], comment: nil)
      /// en translation: Espagnol
      ///
      /// Locales: en, fr
      static let espagnol = Rswift.StringResource(key: "Espagnol", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "fr"], comment: nil)
      /// en translation: French
      ///
      /// Locales: en, fr
      static let french = Rswift.StringResource(key: "French", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "fr"], comment: nil)
      /// en translation: Italian
      ///
      /// Locales: en, fr
      static let italian = Rswift.StringResource(key: "Italian", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "fr"], comment: nil)
      /// en translation: Please check the quality of your network
      ///
      /// Locales: en, fr
      static let netwotkAlert = Rswift.StringResource(key: "netwotkAlert", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "fr"], comment: nil)
      /// en translation: Portugues
      ///
      /// Locales: en, fr
      static let portugues = Rswift.StringResource(key: "Portugues", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "fr"], comment: nil)

      /// en translation:  Arabic
      ///
      /// Locales: en, fr
      static func arabic(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Arabic", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Arabic"
        }

        return NSLocalizedString("Arabic", bundle: bundle, comment: "")
      }

      /// en translation: Add a keyword
      ///
      /// Locales: en, fr
      static func keywords(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("keywords", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "keywords"
        }

        return NSLocalizedString("keywords", bundle: bundle, comment: "")
      }

      /// en translation: Already in favorites
      ///
      /// Locales: en, fr
      static func alertFav(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("alertFav", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "alertFav"
        }

        return NSLocalizedString("alertFav", bundle: bundle, comment: "")
      }

      /// en translation: Choose a languages
      ///
      /// Locales: en, fr
      static func languages(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("languages", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "languages"
        }

        return NSLocalizedString("languages", bundle: bundle, comment: "")
      }

      /// en translation: Choose your categories
      ///
      /// Locales: en, fr
      static func categories(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("categories", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "categories"
        }

        return NSLocalizedString("categories", bundle: bundle, comment: "")
      }

      /// en translation: Deutsch
      ///
      /// Locales: en, fr
      static func deutsch(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Deutsch", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Deutsch"
        }

        return NSLocalizedString("Deutsch", bundle: bundle, comment: "")
      }

      /// en translation: English
      ///
      /// Locales: en, fr
      static func english(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("English", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "English"
        }

        return NSLocalizedString("English", bundle: bundle, comment: "")
      }

      /// en translation: Espagnol
      ///
      /// Locales: en, fr
      static func espagnol(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Espagnol", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Espagnol"
        }

        return NSLocalizedString("Espagnol", bundle: bundle, comment: "")
      }

      /// en translation: French
      ///
      /// Locales: en, fr
      static func french(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("French", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "French"
        }

        return NSLocalizedString("French", bundle: bundle, comment: "")
      }

      /// en translation: Italian
      ///
      /// Locales: en, fr
      static func italian(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Italian", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Italian"
        }

        return NSLocalizedString("Italian", bundle: bundle, comment: "")
      }

      /// en translation: Please check the quality of your network
      ///
      /// Locales: en, fr
      static func netwotkAlert(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("netwotkAlert", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "netwotkAlert"
        }

        return NSLocalizedString("netwotkAlert", bundle: bundle, comment: "")
      }

      /// en translation: Portugues
      ///
      /// Locales: en, fr
      static func portugues(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("Portugues", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "Portugues"
        }

        return NSLocalizedString("Portugues", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try main.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UITabBarController

      let bundle = R.hostingBundle
      let descriptionID = StoryboardViewControllerResource<DescriptionViewController>(identifier: "DescriptionID")
      let favListID = StoryboardViewControllerResource<FavDescriptionViewController>(identifier: "FavListID")
      let name = "Main"
      let resultViewID = StoryboardViewControllerResource<ResultViewController>(identifier: "ResultViewID")

      func descriptionID(_: Void = ()) -> DescriptionViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: descriptionID)
      }

      func favListID(_: Void = ()) -> FavDescriptionViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: favListID)
      }

      func resultViewID(_: Void = ()) -> ResultViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: resultViewID)
      }

      static func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "heart") == nil { throw Rswift.ValidationError(description: "[R.swift] System image named 'heart' is used in storyboard 'Main', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "heart.fill") == nil { throw Rswift.ValidationError(description: "[R.swift] System image named 'heart.fill' is used in storyboard 'Main', but couldn't be loaded.") } }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.main().descriptionID() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'descriptionID' could not be loaded from storyboard 'Main' as 'DescriptionViewController'.") }
        if _R.storyboard.main().favListID() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'favListID' could not be loaded from storyboard 'Main' as 'FavDescriptionViewController'.") }
        if _R.storyboard.main().resultViewID() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'resultViewID' could not be loaded from storyboard 'Main' as 'ResultViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
